### PR TITLE
feat: GitHub Action RET-144

### PR DESCRIPTION
**Pull request by DerekMaggio**
# Overview

Created Github Action for use by other repos. 

# Changelog

- Add action.yml
  - This defines how the Github Action is used by other repos
  - Requires an `ot3-firmware-commit-id` parameter to tell the action where to pull the source for the firmware from
- Update .gitignore to ignore ot3-firmware directory that is pulled in as part of build
- Dockerfile Changes
  - Install prebuilt binary for cmake instead of building from source
  - Add `firmware` build stage
  - Make the apt stuff quieter
- Rename run.sh to build_system.sh
  - Add pulling firmware
  - Add pulling firmware from specific commit
  - Add running headless
- Remove sending stderr to /dev/null in setup_can.sh (It was masking errors) 

# Review requests

None

# Risk assessment

None

### CODE REVIEW

**Comment by DerekMaggio** [comment]
Duplicated from https://github.com/Opentrons/ot3-emulator/pull/10, as I need to link it to a JIRA ticket

**Review by sotaoverride — APPROVED** [review]
Lgtm

**Review by Laura-Danielle — APPROVED** [review]
In general, this PR looks fine to me.

On a higher level, what steps would we need to take to be able to emulate all of the subdirectories in ot3-firmware? I think it would be cool to use the CAN emulator to test sending and receiving messages among all the different fake microcontrollers.

**Comment by DerekMaggio** [comment]
> In general, this PR looks fine to me.
> 
> On a higher level, what steps would we need to take to be able to emulate all of the subdirectories in ot3-firmware? I think it would be cool to use the CAN emulator to test sending and receiving messages among all the different fake microcontrollers.

From my understanding a simulation version of the firmware would need to be provided that maintained state. 
Then you would follow https://github.com/Opentrons/ot3-emulator#adding-more-firmware-containers

**Pull request merged**
